// Mocks generated by Mockito 5.4.6 from annotations
// in aura/test/services/voice_session_service_wakelock_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i3;

import 'package:aura/data/services/posthog_analytics_service.dart' as _i2;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

/// A class which mocks [PostHogAnalyticsService].
///
/// See the documentation for Mockito's code generation for more information.
class MockPostHogAnalyticsService extends _i1.Mock
    implements _i2.PostHogAnalyticsService {
  @override
  _i3.Future<void> trackEvent(
    String? event, {
    Map<String, Object>? properties,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#trackEvent, [event], {#properties: properties}),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);

  @override
  _i3.Future<void> identifyUser(String? uid, {Map<String, Object>? traits}) =>
      (super.noSuchMethod(
            Invocation.method(#identifyUser, [uid], {#traits: traits}),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);

  @override
  _i3.Future<void> screenView(String? screenName) =>
      (super.noSuchMethod(
            Invocation.method(#screenView, [screenName]),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);

  @override
  _i3.Future<void> reset() =>
      (super.noSuchMethod(
            Invocation.method(#reset, []),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);
}
