"""
Screen-save item store — the writer/reader shared by the voice tool
(``agent/voice/screen_saves.py``) and the REST handlers
(``handlers/screen_saves.py``).

One document per save, keyed by a fresh id — items are never merged or
upserted (unlike memory atoms, a screen save is a point-in-time bookmark, not
a fact that gets reinforced). Hard delete, no tombstone, matching
``memory/atom_store.delete_atom`` and ``history.py``'s own delete semantics.
"""

from __future__ import annotations

import asyncio
from datetime import UTC, datetime
from typing import Any

from ...lib.logger import logger
from ..firebase import admin_firestore
from . import fields as F


def _items_ref(uid: str):
    return (
        admin_firestore()
        .collection(F.ITEM_PARENT_COLLECTION).document(uid)
        .collection(F.ITEM_SUBCOLLECTION)
    )


async def create_item(
    uid: str,
    item_id: str,
    *,
    title: str,
    collection_name: str,
    description: str = "",
    note: str = "",
    source_url: str | None = None,
    image_path: str | None = None,
    session_id: str = "",
    source_frame_id: str | None = None,
    now: datetime | None = None,
) -> None:
    """Write one screen_saves item at a caller-supplied id.

    ``item_id`` is generated by the caller (``F.new_item_id()``) rather than
    here, because the SAME id names the GCS object
    (``screen_saves/{uid}/{item_id}.jpg``) that a sibling ``asyncio.gather``
    call uploads concurrently with this write — generating it here would
    force the upload to wait on this write finishing first. Raises on
    failure; wrapped in the caller's own asyncio.gather error handling."""
    now = now or datetime.now(UTC)
    doc = {
        F.TITLE: title.strip()[: F.MAX_TITLE_LENGTH],
        F.DESCRIPTION: (description or "").strip()[: F.MAX_DESCRIPTION_LENGTH],
        F.COLLECTION_NAME: collection_name,
        F.NOTE: (note or "").strip()[: F.MAX_NOTE_LENGTH],
        F.SOURCE_URL: source_url or None,
        F.IMAGE_PATH: image_path or None,
        F.CREATED_AT: now.isoformat(),
        F.SESSION_ID: session_id,
        F.SOURCE_FRAME_ID: source_frame_id or None,
    }
    await asyncio.to_thread(_items_ref(uid).document(item_id).set, doc)


async def clear_image_path(uid: str, item_id: str) -> None:
    """Drop a dangling image_path after its concurrent GCS upload failed, so
    the item still shows up as a saved (text-only) item rather than one whose
    image silently 404s. Never raises — a failed patch just leaves a stale
    reference, no worse than before this call."""
    try:
        await asyncio.to_thread(_items_ref(uid).document(item_id).update, {F.IMAGE_PATH: None})
    except Exception as exc:
        logger.warn("screen_saves.store: clear_image_path failed", {
            "user_id": uid, "item_id": item_id, "error": str(exc),
        })


async def list_items(uid: str, *, limit: int = F.LIST_LIMIT) -> list[dict[str, Any]]:
    """Recent screen saves, newest first, capped. Fails closed (empty list)
    rather than raising, matching history.py's read paths."""
    if not uid:
        return []

    def _read() -> list[dict[str, Any]]:
        query = (
            _items_ref(uid)
            .order_by(F.CREATED_AT, direction="DESCENDING")
            .limit(limit)
        )
        rows: list[dict[str, Any]] = []
        for snap in query.stream():
            data = snap.to_dict() or {}
            rows.append({
                "item_id": snap.id,
                F.TITLE: data.get(F.TITLE, ""),
                F.DESCRIPTION: data.get(F.DESCRIPTION, ""),
                F.COLLECTION_NAME: data.get(F.COLLECTION_NAME, F.DEFAULT_COLLECTION_NAME),
                F.NOTE: data.get(F.NOTE, ""),
                F.SOURCE_URL: data.get(F.SOURCE_URL),
                F.IMAGE_PATH: data.get(F.IMAGE_PATH),
                F.CREATED_AT: data.get(F.CREATED_AT, ""),
            })
        return rows

    try:
        return await asyncio.to_thread(_read)
    except Exception as exc:
        logger.warn("screen_saves.store: list failed", {"user_id": uid, "error": str(exc)})
        return []


async def delete_item(uid: str, item_id: str) -> bool:
    """Hard delete one screen save. Never raises — returns False on failure.
    Does NOT delete the backing GCS object (handlers/screen_saves.py owns
    that, since it also owns the gcs service import)."""
    try:
        await asyncio.to_thread(_items_ref(uid).document(item_id).delete)
        return True
    except Exception as exc:
        logger.warn("screen_saves.store: delete failed", {"user_id": uid, "error": str(exc)})
        return False


async def get_item(uid: str, item_id: str) -> dict[str, Any] | None:
    """One item's raw doc, for the delete handler to find its image_path
    before removing the GCS object. None if missing."""
    def _read() -> dict[str, Any] | None:
        snap = _items_ref(uid).document(item_id).get()
        return (snap.to_dict() or {}) if snap.exists else None

    try:
        return await asyncio.to_thread(_read)
    except Exception as exc:
        logger.warn("screen_saves.store: get failed", {"user_id": uid, "error": str(exc)})
        return None
