// Mocks generated by Mockito 5.4.6 from annotations
// in aura/test/repositories/chat_repository_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i3;

import 'package:aura/data/services/chat_backup_service.dart' as _i2;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

/// A class which mocks [ChatBackupService].
///
/// See the documentation for Mockito's code generation for more information.
class MockChatBackupService extends _i1.Mock implements _i2.ChatBackupService {
  @override
  _i3.Future<void> enqueueMessageUpsert({
    required String? userId,
    required String? sessionId,
    required String? messageId,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#enqueueMessageUpsert, [], {
              #userId: userId,
              #sessionId: sessionId,
              #messageId: messageId,
            }),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);

  @override
  _i3.Future<void> enqueueSessionUpsert({
    required String? userId,
    required String? sessionId,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#enqueueSessionUpsert, [], {
              #userId: userId,
              #sessionId: sessionId,
            }),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);

  @override
  _i3.Future<void> processPendingJobs({String? userId}) =>
      (super.noSuchMethod(
            Invocation.method(#processPendingJobs, [], {#userId: userId}),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);

  @override
  _i3.Future<bool> restoreSessionMessagesIfEmpty(
    String? userId,
    String? sessionId,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#restoreSessionMessagesIfEmpty, [
              userId,
              sessionId,
            ]),
            returnValue: _i3.Future<bool>.value(false),
            returnValueForMissingStub: _i3.Future<bool>.value(false),
          )
          as _i3.Future<bool>);

  @override
  _i3.Future<_i2.ServerReply?> fetchServerReply(
    String? userId,
    String? clientMessageId,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#fetchServerReply, [userId, clientMessageId]),
            returnValue: _i3.Future<_i2.ServerReply?>.value(),
            returnValueForMissingStub: _i3.Future<_i2.ServerReply?>.value(),
          )
          as _i3.Future<_i2.ServerReply?>);

  @override
  _i3.Future<bool> restoreFromBackupIfLocalEmpty(String? userId) =>
      (super.noSuchMethod(
            Invocation.method(#restoreFromBackupIfLocalEmpty, [userId]),
            returnValue: _i3.Future<bool>.value(false),
            returnValueForMissingStub: _i3.Future<bool>.value(false),
          )
          as _i3.Future<bool>);

  @override
  _i3.Future<void> backfillUnsynced(String? userId) =>
      (super.noSuchMethod(
            Invocation.method(#backfillUnsynced, [userId]),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);
}
