// Mocks generated by Mockito 5.4.6 from annotations
// in aura/test/viewmodels/auth_viewmodel_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i3;

import 'package:aura/core/network/api_response.dart' as _i6;
import 'package:aura/data/models/chat_attachment.dart' as _i10;
import 'package:aura/data/models/daily_briefing.dart' as _i11;
import 'package:aura/data/models/user_model.dart' as _i5;
import 'package:aura/data/repositories/auth_repository.dart' as _i2;
import 'package:aura/data/services/backend_api_service.dart' as _i9;
import 'package:aura/data/services/notification_service.dart' as _i8;
import 'package:aura/data/services/posthog_analytics_service.dart' as _i12;
import 'package:firebase_auth/firebase_auth.dart' as _i4;
import 'package:mockito/mockito.dart' as _i1;
import 'package:mockito/src/dummies.dart' as _i7;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

/// A class which mocks [AuthRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockAuthRepository extends _i1.Mock implements _i2.AuthRepository {
  @override
  _i3.Stream<_i4.User?> get authStateStream =>
      (super.noSuchMethod(
            Invocation.getter(#authStateStream),
            returnValue: _i3.Stream<_i4.User?>.empty(),
            returnValueForMissingStub: _i3.Stream<_i4.User?>.empty(),
          )
          as _i3.Stream<_i4.User?>);

  @override
  _i3.Stream<_i5.UserModel?> get userModelStream =>
      (super.noSuchMethod(
            Invocation.getter(#userModelStream),
            returnValue: _i3.Stream<_i5.UserModel?>.empty(),
            returnValueForMissingStub: _i3.Stream<_i5.UserModel?>.empty(),
          )
          as _i3.Stream<_i5.UserModel?>);

  @override
  _i3.Future<_i6.Result<_i5.UserModel>> signInWithGoogle() =>
      (super.noSuchMethod(
            Invocation.method(#signInWithGoogle, []),
            returnValue: _i3.Future<_i6.Result<_i5.UserModel>>.value(
              _i7.dummyValue<_i6.Result<_i5.UserModel>>(
                this,
                Invocation.method(#signInWithGoogle, []),
              ),
            ),
            returnValueForMissingStub:
                _i3.Future<_i6.Result<_i5.UserModel>>.value(
                  _i7.dummyValue<_i6.Result<_i5.UserModel>>(
                    this,
                    Invocation.method(#signInWithGoogle, []),
                  ),
                ),
          )
          as _i3.Future<_i6.Result<_i5.UserModel>>);

  @override
  _i3.Future<_i6.Result<_i5.UserModel>> signInWithApple() =>
      (super.noSuchMethod(
            Invocation.method(#signInWithApple, []),
            returnValue: _i3.Future<_i6.Result<_i5.UserModel>>.value(
              _i7.dummyValue<_i6.Result<_i5.UserModel>>(
                this,
                Invocation.method(#signInWithApple, []),
              ),
            ),
            returnValueForMissingStub:
                _i3.Future<_i6.Result<_i5.UserModel>>.value(
                  _i7.dummyValue<_i6.Result<_i5.UserModel>>(
                    this,
                    Invocation.method(#signInWithApple, []),
                  ),
                ),
          )
          as _i3.Future<_i6.Result<_i5.UserModel>>);

  @override
  _i3.Future<_i6.Result<_i5.UserModel?>> getCurrentUser() =>
      (super.noSuchMethod(
            Invocation.method(#getCurrentUser, []),
            returnValue: _i3.Future<_i6.Result<_i5.UserModel?>>.value(
              _i7.dummyValue<_i6.Result<_i5.UserModel?>>(
                this,
                Invocation.method(#getCurrentUser, []),
              ),
            ),
            returnValueForMissingStub:
                _i3.Future<_i6.Result<_i5.UserModel?>>.value(
                  _i7.dummyValue<_i6.Result<_i5.UserModel?>>(
                    this,
                    Invocation.method(#getCurrentUser, []),
                  ),
                ),
          )
          as _i3.Future<_i6.Result<_i5.UserModel?>>);

  @override
  _i3.Future<_i6.Result<_i5.UserModel>> signInWithEmail(
    String? email,
    String? password,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#signInWithEmail, [email, password]),
            returnValue: _i3.Future<_i6.Result<_i5.UserModel>>.value(
              _i7.dummyValue<_i6.Result<_i5.UserModel>>(
                this,
                Invocation.method(#signInWithEmail, [email, password]),
              ),
            ),
            returnValueForMissingStub:
                _i3.Future<_i6.Result<_i5.UserModel>>.value(
                  _i7.dummyValue<_i6.Result<_i5.UserModel>>(
                    this,
                    Invocation.method(#signInWithEmail, [email, password]),
                  ),
                ),
          )
          as _i3.Future<_i6.Result<_i5.UserModel>>);

  @override
  _i3.Future<_i6.Result<_i5.UserModel>> createAccountWithEmail(
    String? email,
    String? password,
    String? name,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#createAccountWithEmail, [email, password, name]),
            returnValue: _i3.Future<_i6.Result<_i5.UserModel>>.value(
              _i7.dummyValue<_i6.Result<_i5.UserModel>>(
                this,
                Invocation.method(#createAccountWithEmail, [
                  email,
                  password,
                  name,
                ]),
              ),
            ),
            returnValueForMissingStub:
                _i3.Future<_i6.Result<_i5.UserModel>>.value(
                  _i7.dummyValue<_i6.Result<_i5.UserModel>>(
                    this,
                    Invocation.method(#createAccountWithEmail, [
                      email,
                      password,
                      name,
                    ]),
                  ),
                ),
          )
          as _i3.Future<_i6.Result<_i5.UserModel>>);

  @override
  _i3.Future<_i6.Result<void>> signOut() =>
      (super.noSuchMethod(
            Invocation.method(#signOut, []),
            returnValue: _i3.Future<_i6.Result<void>>.value(
              _i7.dummyValue<_i6.Result<void>>(
                this,
                Invocation.method(#signOut, []),
              ),
            ),
            returnValueForMissingStub: _i3.Future<_i6.Result<void>>.value(
              _i7.dummyValue<_i6.Result<void>>(
                this,
                Invocation.method(#signOut, []),
              ),
            ),
          )
          as _i3.Future<_i6.Result<void>>);

  @override
  _i3.Future<_i6.Result<void>> setAuraConsentGranted(
    String? uid,
    bool? granted,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#setAuraConsentGranted, [uid, granted]),
            returnValue: _i3.Future<_i6.Result<void>>.value(
              _i7.dummyValue<_i6.Result<void>>(
                this,
                Invocation.method(#setAuraConsentGranted, [uid, granted]),
              ),
            ),
            returnValueForMissingStub: _i3.Future<_i6.Result<void>>.value(
              _i7.dummyValue<_i6.Result<void>>(
                this,
                Invocation.method(#setAuraConsentGranted, [uid, granted]),
              ),
            ),
          )
          as _i3.Future<_i6.Result<void>>);

  @override
  _i3.Future<String?> getIdToken() =>
      (super.noSuchMethod(
            Invocation.method(#getIdToken, []),
            returnValue: _i3.Future<String?>.value(),
            returnValueForMissingStub: _i3.Future<String?>.value(),
          )
          as _i3.Future<String?>);
}

/// A class which mocks [NotificationService].
///
/// See the documentation for Mockito's code generation for more information.
class MockNotificationService extends _i1.Mock
    implements _i8.NotificationService {
  @override
  _i3.Stream<_i8.EngagementTapPayload> get engagementTapStream =>
      (super.noSuchMethod(
            Invocation.getter(#engagementTapStream),
            returnValue: _i3.Stream<_i8.EngagementTapPayload>.empty(),
            returnValueForMissingStub:
                _i3.Stream<_i8.EngagementTapPayload>.empty(),
          )
          as _i3.Stream<_i8.EngagementTapPayload>);

  @override
  _i3.Stream<_i8.SignalNotificationTapPayload>
  get signalNotificationTapStream =>
      (super.noSuchMethod(
            Invocation.getter(#signalNotificationTapStream),
            returnValue: _i3.Stream<_i8.SignalNotificationTapPayload>.empty(),
            returnValueForMissingStub:
                _i3.Stream<_i8.SignalNotificationTapPayload>.empty(),
          )
          as _i3.Stream<_i8.SignalNotificationTapPayload>);

  @override
  _i3.Stream<_i8.ThreadFollowUpTapPayload> get threadFollowUpTapStream =>
      (super.noSuchMethod(
            Invocation.getter(#threadFollowUpTapStream),
            returnValue: _i3.Stream<_i8.ThreadFollowUpTapPayload>.empty(),
            returnValueForMissingStub:
                _i3.Stream<_i8.ThreadFollowUpTapPayload>.empty(),
          )
          as _i3.Stream<_i8.ThreadFollowUpTapPayload>);

  @override
  _i3.Stream<_i8.IcebreakerTapPayload> get icebreakerTapStream =>
      (super.noSuchMethod(
            Invocation.getter(#icebreakerTapStream),
            returnValue: _i3.Stream<_i8.IcebreakerTapPayload>.empty(),
            returnValueForMissingStub:
                _i3.Stream<_i8.IcebreakerTapPayload>.empty(),
          )
          as _i3.Stream<_i8.IcebreakerTapPayload>);

  @override
  _i3.Stream<_i8.DailyBriefingTapPayload> get dailyBriefingTapStream =>
      (super.noSuchMethod(
            Invocation.getter(#dailyBriefingTapStream),
            returnValue: _i3.Stream<_i8.DailyBriefingTapPayload>.empty(),
            returnValueForMissingStub:
                _i3.Stream<_i8.DailyBriefingTapPayload>.empty(),
          )
          as _i3.Stream<_i8.DailyBriefingTapPayload>);

  @override
  _i3.Stream<_i8.TrackerUpdateTapPayload> get trackerUpdateTapStream =>
      (super.noSuchMethod(
            Invocation.getter(#trackerUpdateTapStream),
            returnValue: _i3.Stream<_i8.TrackerUpdateTapPayload>.empty(),
            returnValueForMissingStub:
                _i3.Stream<_i8.TrackerUpdateTapPayload>.empty(),
          )
          as _i3.Stream<_i8.TrackerUpdateTapPayload>);

  @override
  _i3.Stream<_i8.ChatReplyTapPayload> get chatReplyTapStream =>
      (super.noSuchMethod(
            Invocation.getter(#chatReplyTapStream),
            returnValue: _i3.Stream<_i8.ChatReplyTapPayload>.empty(),
            returnValueForMissingStub:
                _i3.Stream<_i8.ChatReplyTapPayload>.empty(),
          )
          as _i3.Stream<_i8.ChatReplyTapPayload>);

  @override
  _i3.Stream<_i8.TrialTapPayload> get trialTapStream =>
      (super.noSuchMethod(
            Invocation.getter(#trialTapStream),
            returnValue: _i3.Stream<_i8.TrialTapPayload>.empty(),
            returnValueForMissingStub: _i3.Stream<_i8.TrialTapPayload>.empty(),
          )
          as _i3.Stream<_i8.TrialTapPayload>);

  @override
  _i3.Stream<_i8.EntitlementUpdatedPayload> get entitlementUpdatedStream =>
      (super.noSuchMethod(
            Invocation.getter(#entitlementUpdatedStream),
            returnValue: _i3.Stream<_i8.EntitlementUpdatedPayload>.empty(),
            returnValueForMissingStub:
                _i3.Stream<_i8.EntitlementUpdatedPayload>.empty(),
          )
          as _i3.Stream<_i8.EntitlementUpdatedPayload>);

  @override
  _i3.Future<void> initialize(String? userId) =>
      (super.noSuchMethod(
            Invocation.method(#initialize, [userId]),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);

  @override
  _i3.Future<void> dispose() =>
      (super.noSuchMethod(
            Invocation.method(#dispose, []),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);

  @override
  _i3.Future<void> reportContentSkipped({
    required String? contentId,
    String? category,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#reportContentSkipped, [], {
              #contentId: contentId,
              #category: category,
            }),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);

  @override
  _i3.Future<void> reportContentOpened({
    required String? contentId,
    String? category,
    String? notificationId,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#reportContentOpened, [], {
              #contentId: contentId,
              #category: category,
              #notificationId: notificationId,
            }),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);

  @override
  _i3.Future<void> reportAppOpen() =>
      (super.noSuchMethod(
            Invocation.method(#reportAppOpen, []),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);

  @override
  void dispatchNotificationTap(Map<String, dynamic>? data) =>
      super.noSuchMethod(
        Invocation.method(#dispatchNotificationTap, [data]),
        returnValueForMissingStub: null,
      );

  @override
  _i3.Future<String?> getToken() =>
      (super.noSuchMethod(
            Invocation.method(#getToken, []),
            returnValue: _i3.Future<String?>.value(),
            returnValueForMissingStub: _i3.Future<String?>.value(),
          )
          as _i3.Future<String?>);
}

/// A class which mocks [BackendApiService].
///
/// See the documentation for Mockito's code generation for more information.
class MockBackendApiService extends _i1.Mock implements _i9.BackendApiService {
  @override
  _i3.Future<_i6.Result<_i9.ChatResponse>> sendMessage(
    String? message,
    String? userId, {
    List<Map<String, dynamic>>? history = const [],
    String? sessionId,
    String? clientMessageId,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #sendMessage,
              [message, userId],
              {
                #history: history,
                #sessionId: sessionId,
                #clientMessageId: clientMessageId,
              },
            ),
            returnValue: _i3.Future<_i6.Result<_i9.ChatResponse>>.value(
              _i7.dummyValue<_i6.Result<_i9.ChatResponse>>(
                this,
                Invocation.method(
                  #sendMessage,
                  [message, userId],
                  {
                    #history: history,
                    #sessionId: sessionId,
                    #clientMessageId: clientMessageId,
                  },
                ),
              ),
            ),
            returnValueForMissingStub:
                _i3.Future<_i6.Result<_i9.ChatResponse>>.value(
                  _i7.dummyValue<_i6.Result<_i9.ChatResponse>>(
                    this,
                    Invocation.method(
                      #sendMessage,
                      [message, userId],
                      {
                        #history: history,
                        #sessionId: sessionId,
                        #clientMessageId: clientMessageId,
                      },
                    ),
                  ),
                ),
          )
          as _i3.Future<_i6.Result<_i9.ChatResponse>>);

  @override
  _i3.Stream<_i9.ChatStreamEvent> sendMessageStream(
    String? message,
    String? userId, {
    List<Map<String, dynamic>>? history = const [],
    String? sessionId,
    String? clientMessageId,
    String? agentId,
    List<_i10.ChatAttachment>? attachments,
    String? notificationReason,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #sendMessageStream,
              [message, userId],
              {
                #history: history,
                #sessionId: sessionId,
                #clientMessageId: clientMessageId,
                #agentId: agentId,
                #attachments: attachments,
                #notificationReason: notificationReason,
              },
            ),
            returnValue: _i3.Stream<_i9.ChatStreamEvent>.empty(),
            returnValueForMissingStub: _i3.Stream<_i9.ChatStreamEvent>.empty(),
          )
          as _i3.Stream<_i9.ChatStreamEvent>);

  @override
  _i3.Future<void> markEngagementResponded(String? engagementId) =>
      (super.noSuchMethod(
            Invocation.method(#markEngagementResponded, [engagementId]),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);

  @override
  _i3.Future<_i6.Result<void>> deleteAccount() =>
      (super.noSuchMethod(
            Invocation.method(#deleteAccount, []),
            returnValue: _i3.Future<_i6.Result<void>>.value(
              _i7.dummyValue<_i6.Result<void>>(
                this,
                Invocation.method(#deleteAccount, []),
              ),
            ),
            returnValueForMissingStub: _i3.Future<_i6.Result<void>>.value(
              _i7.dummyValue<_i6.Result<void>>(
                this,
                Invocation.method(#deleteAccount, []),
              ),
            ),
          )
          as _i3.Future<_i6.Result<void>>);

  @override
  _i3.Future<_i6.Result<Map<String, dynamic>>> refreshBuddyPills() =>
      (super.noSuchMethod(
            Invocation.method(#refreshBuddyPills, []),
            returnValue: _i3.Future<_i6.Result<Map<String, dynamic>>>.value(
              _i7.dummyValue<_i6.Result<Map<String, dynamic>>>(
                this,
                Invocation.method(#refreshBuddyPills, []),
              ),
            ),
            returnValueForMissingStub:
                _i3.Future<_i6.Result<Map<String, dynamic>>>.value(
                  _i7.dummyValue<_i6.Result<Map<String, dynamic>>>(
                    this,
                    Invocation.method(#refreshBuddyPills, []),
                  ),
                ),
          )
          as _i3.Future<_i6.Result<Map<String, dynamic>>>);

  @override
  _i3.Future<_i6.Result<Map<String, dynamic>>> startDevicePairing() =>
      (super.noSuchMethod(
            Invocation.method(#startDevicePairing, []),
            returnValue: _i3.Future<_i6.Result<Map<String, dynamic>>>.value(
              _i7.dummyValue<_i6.Result<Map<String, dynamic>>>(
                this,
                Invocation.method(#startDevicePairing, []),
              ),
            ),
            returnValueForMissingStub:
                _i3.Future<_i6.Result<Map<String, dynamic>>>.value(
                  _i7.dummyValue<_i6.Result<Map<String, dynamic>>>(
                    this,
                    Invocation.method(#startDevicePairing, []),
                  ),
                ),
          )
          as _i3.Future<_i6.Result<Map<String, dynamic>>>);

  @override
  _i3.Future<_i6.Result<Map<String, dynamic>>> unlinkDevice(String? deviceId) =>
      (super.noSuchMethod(
            Invocation.method(#unlinkDevice, [deviceId]),
            returnValue: _i3.Future<_i6.Result<Map<String, dynamic>>>.value(
              _i7.dummyValue<_i6.Result<Map<String, dynamic>>>(
                this,
                Invocation.method(#unlinkDevice, [deviceId]),
              ),
            ),
            returnValueForMissingStub:
                _i3.Future<_i6.Result<Map<String, dynamic>>>.value(
                  _i7.dummyValue<_i6.Result<Map<String, dynamic>>>(
                    this,
                    Invocation.method(#unlinkDevice, [deviceId]),
                  ),
                ),
          )
          as _i3.Future<_i6.Result<Map<String, dynamic>>>);

  @override
  _i3.Future<_i6.Result<Map<String, dynamic>>> consolidateSession({
    required String? sessionId,
    required List<Map<String, dynamic>>? turns,
    String? modality = 'text',
  }) =>
      (super.noSuchMethod(
            Invocation.method(#consolidateSession, [], {
              #sessionId: sessionId,
              #turns: turns,
              #modality: modality,
            }),
            returnValue: _i3.Future<_i6.Result<Map<String, dynamic>>>.value(
              _i7.dummyValue<_i6.Result<Map<String, dynamic>>>(
                this,
                Invocation.method(#consolidateSession, [], {
                  #sessionId: sessionId,
                  #turns: turns,
                  #modality: modality,
                }),
              ),
            ),
            returnValueForMissingStub:
                _i3.Future<_i6.Result<Map<String, dynamic>>>.value(
                  _i7.dummyValue<_i6.Result<Map<String, dynamic>>>(
                    this,
                    Invocation.method(#consolidateSession, [], {
                      #sessionId: sessionId,
                      #turns: turns,
                      #modality: modality,
                    }),
                  ),
                ),
          )
          as _i3.Future<_i6.Result<Map<String, dynamic>>>);

  @override
  _i3.Future<_i6.Result<Map<String, dynamic>>> seedOnboardingInterests(
    List<String>? interestSlugs,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#seedOnboardingInterests, [interestSlugs]),
            returnValue: _i3.Future<_i6.Result<Map<String, dynamic>>>.value(
              _i7.dummyValue<_i6.Result<Map<String, dynamic>>>(
                this,
                Invocation.method(#seedOnboardingInterests, [interestSlugs]),
              ),
            ),
            returnValueForMissingStub:
                _i3.Future<_i6.Result<Map<String, dynamic>>>.value(
                  _i7.dummyValue<_i6.Result<Map<String, dynamic>>>(
                    this,
                    Invocation.method(#seedOnboardingInterests, [
                      interestSlugs,
                    ]),
                  ),
                ),
          )
          as _i3.Future<_i6.Result<Map<String, dynamic>>>);

  @override
  _i3.Future<_i6.Result<Map<String, dynamic>>> postSignalEvents(
    List<Map<String, dynamic>>? events,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#postSignalEvents, [events]),
            returnValue: _i3.Future<_i6.Result<Map<String, dynamic>>>.value(
              _i7.dummyValue<_i6.Result<Map<String, dynamic>>>(
                this,
                Invocation.method(#postSignalEvents, [events]),
              ),
            ),
            returnValueForMissingStub:
                _i3.Future<_i6.Result<Map<String, dynamic>>>.value(
                  _i7.dummyValue<_i6.Result<Map<String, dynamic>>>(
                    this,
                    Invocation.method(#postSignalEvents, [events]),
                  ),
                ),
          )
          as _i3.Future<_i6.Result<Map<String, dynamic>>>);

  @override
  _i3.Future<List<Map<String, dynamic>>> fetchThreadMessages(
    String? threadId,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#fetchThreadMessages, [threadId]),
            returnValue: _i3.Future<List<Map<String, dynamic>>>.value(
              <Map<String, dynamic>>[],
            ),
            returnValueForMissingStub:
                _i3.Future<List<Map<String, dynamic>>>.value(
                  <Map<String, dynamic>>[],
                ),
          )
          as _i3.Future<List<Map<String, dynamic>>>);

  @override
  _i3.Future<_i11.DailyBriefing?> fetchTodayBriefing() =>
      (super.noSuchMethod(
            Invocation.method(#fetchTodayBriefing, []),
            returnValue: _i3.Future<_i11.DailyBriefing?>.value(),
            returnValueForMissingStub: _i3.Future<_i11.DailyBriefing?>.value(),
          )
          as _i3.Future<_i11.DailyBriefing?>);

  @override
  _i3.Future<_i11.DailyBriefing?> generateTodayBriefing({
    bool? force = false,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#generateTodayBriefing, [], {#force: force}),
            returnValue: _i3.Future<_i11.DailyBriefing?>.value(),
            returnValueForMissingStub: _i3.Future<_i11.DailyBriefing?>.value(),
          )
          as _i3.Future<_i11.DailyBriefing?>);

  @override
  _i3.Future<_i11.DailyBriefing?> fetchWorldBriefing({bool? refresh = false}) =>
      (super.noSuchMethod(
            Invocation.method(#fetchWorldBriefing, [], {#refresh: refresh}),
            returnValue: _i3.Future<_i11.DailyBriefing?>.value(),
            returnValueForMissingStub: _i3.Future<_i11.DailyBriefing?>.value(),
          )
          as _i3.Future<_i11.DailyBriefing?>);
}

/// A class which mocks [PostHogAnalyticsService].
///
/// See the documentation for Mockito's code generation for more information.
class MockPostHogAnalyticsService extends _i1.Mock
    implements _i12.PostHogAnalyticsService {
  @override
  _i3.Future<void> trackEvent(
    String? event, {
    Map<String, Object>? properties,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#trackEvent, [event], {#properties: properties}),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);

  @override
  _i3.Future<void> identifyUser(String? uid, {Map<String, Object>? traits}) =>
      (super.noSuchMethod(
            Invocation.method(#identifyUser, [uid], {#traits: traits}),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);

  @override
  _i3.Future<void> screenView(String? screenName) =>
      (super.noSuchMethod(
            Invocation.method(#screenView, [screenName]),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);

  @override
  _i3.Future<void> reset() =>
      (super.noSuchMethod(
            Invocation.method(#reset, []),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);
}
