// Mocks generated by Mockito 5.4.6 from annotations
// in aura/test/viewmodels/briefing_viewmodel_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i3;

import 'package:aura/core/network/api_response.dart' as _i4;
import 'package:aura/data/models/chat_attachment.dart' as _i6;
import 'package:aura/data/models/daily_briefing.dart' as _i7;
import 'package:aura/data/services/backend_api_service.dart' as _i2;
import 'package:aura/data/services/posthog_analytics_service.dart' as _i8;
import 'package:mockito/mockito.dart' as _i1;
import 'package:mockito/src/dummies.dart' as _i5;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

/// A class which mocks [BackendApiService].
///
/// See the documentation for Mockito's code generation for more information.
class MockBackendApiService extends _i1.Mock implements _i2.BackendApiService {
  @override
  _i3.Future<_i4.Result<_i2.ChatResponse>> sendMessage(
    String? message,
    String? userId, {
    List<Map<String, dynamic>>? history = const [],
    String? sessionId,
    String? clientMessageId,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #sendMessage,
              [message, userId],
              {
                #history: history,
                #sessionId: sessionId,
                #clientMessageId: clientMessageId,
              },
            ),
            returnValue: _i3.Future<_i4.Result<_i2.ChatResponse>>.value(
              _i5.dummyValue<_i4.Result<_i2.ChatResponse>>(
                this,
                Invocation.method(
                  #sendMessage,
                  [message, userId],
                  {
                    #history: history,
                    #sessionId: sessionId,
                    #clientMessageId: clientMessageId,
                  },
                ),
              ),
            ),
            returnValueForMissingStub:
                _i3.Future<_i4.Result<_i2.ChatResponse>>.value(
                  _i5.dummyValue<_i4.Result<_i2.ChatResponse>>(
                    this,
                    Invocation.method(
                      #sendMessage,
                      [message, userId],
                      {
                        #history: history,
                        #sessionId: sessionId,
                        #clientMessageId: clientMessageId,
                      },
                    ),
                  ),
                ),
          )
          as _i3.Future<_i4.Result<_i2.ChatResponse>>);

  @override
  _i3.Stream<_i2.ChatStreamEvent> sendMessageStream(
    String? message,
    String? userId, {
    List<Map<String, dynamic>>? history = const [],
    String? sessionId,
    String? clientMessageId,
    String? agentId,
    List<_i6.ChatAttachment>? attachments,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #sendMessageStream,
              [message, userId],
              {
                #history: history,
                #sessionId: sessionId,
                #clientMessageId: clientMessageId,
                #agentId: agentId,
                #attachments: attachments,
              },
            ),
            returnValue: _i3.Stream<_i2.ChatStreamEvent>.empty(),
            returnValueForMissingStub: _i3.Stream<_i2.ChatStreamEvent>.empty(),
          )
          as _i3.Stream<_i2.ChatStreamEvent>);

  @override
  _i3.Future<void> markEngagementResponded(String? engagementId) =>
      (super.noSuchMethod(
            Invocation.method(#markEngagementResponded, [engagementId]),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);

  @override
  _i3.Future<_i4.Result<void>> deleteAccount() =>
      (super.noSuchMethod(
            Invocation.method(#deleteAccount, []),
            returnValue: _i3.Future<_i4.Result<void>>.value(
              _i5.dummyValue<_i4.Result<void>>(
                this,
                Invocation.method(#deleteAccount, []),
              ),
            ),
            returnValueForMissingStub: _i3.Future<_i4.Result<void>>.value(
              _i5.dummyValue<_i4.Result<void>>(
                this,
                Invocation.method(#deleteAccount, []),
              ),
            ),
          )
          as _i3.Future<_i4.Result<void>>);

  @override
  _i3.Future<_i4.Result<Map<String, dynamic>>> refreshBuddyPills() =>
      (super.noSuchMethod(
            Invocation.method(#refreshBuddyPills, []),
            returnValue: _i3.Future<_i4.Result<Map<String, dynamic>>>.value(
              _i5.dummyValue<_i4.Result<Map<String, dynamic>>>(
                this,
                Invocation.method(#refreshBuddyPills, []),
              ),
            ),
            returnValueForMissingStub:
                _i3.Future<_i4.Result<Map<String, dynamic>>>.value(
                  _i5.dummyValue<_i4.Result<Map<String, dynamic>>>(
                    this,
                    Invocation.method(#refreshBuddyPills, []),
                  ),
                ),
          )
          as _i3.Future<_i4.Result<Map<String, dynamic>>>);

  @override
  _i3.Future<_i4.Result<Map<String, dynamic>>> seedOnboardingInterests(
    List<String>? interestSlugs,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#seedOnboardingInterests, [interestSlugs]),
            returnValue: _i3.Future<_i4.Result<Map<String, dynamic>>>.value(
              _i5.dummyValue<_i4.Result<Map<String, dynamic>>>(
                this,
                Invocation.method(#seedOnboardingInterests, [interestSlugs]),
              ),
            ),
            returnValueForMissingStub:
                _i3.Future<_i4.Result<Map<String, dynamic>>>.value(
                  _i5.dummyValue<_i4.Result<Map<String, dynamic>>>(
                    this,
                    Invocation.method(#seedOnboardingInterests, [
                      interestSlugs,
                    ]),
                  ),
                ),
          )
          as _i3.Future<_i4.Result<Map<String, dynamic>>>);

  @override
  _i3.Future<_i4.Result<Map<String, dynamic>>> postSignalEvents(
    List<Map<String, dynamic>>? events,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#postSignalEvents, [events]),
            returnValue: _i3.Future<_i4.Result<Map<String, dynamic>>>.value(
              _i5.dummyValue<_i4.Result<Map<String, dynamic>>>(
                this,
                Invocation.method(#postSignalEvents, [events]),
              ),
            ),
            returnValueForMissingStub:
                _i3.Future<_i4.Result<Map<String, dynamic>>>.value(
                  _i5.dummyValue<_i4.Result<Map<String, dynamic>>>(
                    this,
                    Invocation.method(#postSignalEvents, [events]),
                  ),
                ),
          )
          as _i3.Future<_i4.Result<Map<String, dynamic>>>);

  @override
  _i3.Future<List<Map<String, dynamic>>> fetchThreadMessages(
    String? threadId,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#fetchThreadMessages, [threadId]),
            returnValue: _i3.Future<List<Map<String, dynamic>>>.value(
              <Map<String, dynamic>>[],
            ),
            returnValueForMissingStub:
                _i3.Future<List<Map<String, dynamic>>>.value(
                  <Map<String, dynamic>>[],
                ),
          )
          as _i3.Future<List<Map<String, dynamic>>>);

  @override
  _i3.Future<_i7.DailyBriefing?> fetchTodayBriefing() =>
      (super.noSuchMethod(
            Invocation.method(#fetchTodayBriefing, []),
            returnValue: _i3.Future<_i7.DailyBriefing?>.value(),
            returnValueForMissingStub: _i3.Future<_i7.DailyBriefing?>.value(),
          )
          as _i3.Future<_i7.DailyBriefing?>);

  @override
  _i3.Future<_i7.DailyBriefing?> generateTodayBriefing({bool? force = false}) =>
      (super.noSuchMethod(
            Invocation.method(#generateTodayBriefing, [], {#force: force}),
            returnValue: _i3.Future<_i7.DailyBriefing?>.value(),
            returnValueForMissingStub: _i3.Future<_i7.DailyBriefing?>.value(),
          )
          as _i3.Future<_i7.DailyBriefing?>);

  @override
  _i3.Future<_i7.DailyBriefing?> fetchWorldBriefing({bool? refresh = false}) =>
      (super.noSuchMethod(
            Invocation.method(#fetchWorldBriefing, [], {#refresh: refresh}),
            returnValue: _i3.Future<_i7.DailyBriefing?>.value(),
            returnValueForMissingStub: _i3.Future<_i7.DailyBriefing?>.value(),
          )
          as _i3.Future<_i7.DailyBriefing?>);
}

/// A class which mocks [PostHogAnalyticsService].
///
/// See the documentation for Mockito's code generation for more information.
class MockPostHogAnalyticsService extends _i1.Mock
    implements _i8.PostHogAnalyticsService {
  @override
  _i3.Future<void> trackEvent(
    String? event, {
    Map<String, Object>? properties,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#trackEvent, [event], {#properties: properties}),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);

  @override
  _i3.Future<void> identifyUser(String? uid, {Map<String, Object>? traits}) =>
      (super.noSuchMethod(
            Invocation.method(#identifyUser, [uid], {#traits: traits}),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);

  @override
  _i3.Future<void> screenView(String? screenName) =>
      (super.noSuchMethod(
            Invocation.method(#screenView, [screenName]),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);

  @override
  _i3.Future<void> reset() =>
      (super.noSuchMethod(
            Invocation.method(#reset, []),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);
}
