// Mocks generated by Mockito 5.4.6 from annotations
// in aura/test/viewmodels/desktop_voice_viewmodel_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i3;
import 'dart:typed_data' as _i7;

import 'package:aura/core/network/api_response.dart' as _i5;
import 'package:aura/data/local/app_database.dart' as _i9;
import 'package:aura/data/models/chat_message_model.dart' as _i10;
import 'package:aura/data/models/voice_models.dart' as _i4;
import 'package:aura/data/repositories/chat_repository.dart' as _i8;
import 'package:aura/data/services/voice_session_service.dart' as _i2;
import 'package:mockito/mockito.dart' as _i1;
import 'package:mockito/src/dummies.dart' as _i6;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

/// A class which mocks [VoiceSessionService].
///
/// See the documentation for Mockito's code generation for more information.
class MockVoiceSessionService extends _i1.Mock
    implements _i2.VoiceSessionService {
  @override
  _i3.Stream<_i4.VoiceServerEvent> get events =>
      (super.noSuchMethod(
            Invocation.getter(#events),
            returnValue: _i3.Stream<_i4.VoiceServerEvent>.empty(),
            returnValueForMissingStub: _i3.Stream<_i4.VoiceServerEvent>.empty(),
          )
          as _i3.Stream<_i4.VoiceServerEvent>);

  @override
  bool get isConnected =>
      (super.noSuchMethod(
            Invocation.getter(#isConnected),
            returnValue: false,
            returnValueForMissingStub: false,
          )
          as bool);

  @override
  _i3.Future<void> prewarm() =>
      (super.noSuchMethod(
            Invocation.method(#prewarm, []),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);

  @override
  _i3.Future<_i5.Result<void>> startSession(_i4.VoiceSessionConfig? config) =>
      (super.noSuchMethod(
            Invocation.method(#startSession, [config]),
            returnValue: _i3.Future<_i5.Result<void>>.value(
              _i6.dummyValue<_i5.Result<void>>(
                this,
                Invocation.method(#startSession, [config]),
              ),
            ),
            returnValueForMissingStub: _i3.Future<_i5.Result<void>>.value(
              _i6.dummyValue<_i5.Result<void>>(
                this,
                Invocation.method(#startSession, [config]),
              ),
            ),
          )
          as _i3.Future<_i5.Result<void>>);

  @override
  _i3.Future<_i5.Result<void>> sendTextInput(String? text) =>
      (super.noSuchMethod(
            Invocation.method(#sendTextInput, [text]),
            returnValue: _i3.Future<_i5.Result<void>>.value(
              _i6.dummyValue<_i5.Result<void>>(
                this,
                Invocation.method(#sendTextInput, [text]),
              ),
            ),
            returnValueForMissingStub: _i3.Future<_i5.Result<void>>.value(
              _i6.dummyValue<_i5.Result<void>>(
                this,
                Invocation.method(#sendTextInput, [text]),
              ),
            ),
          )
          as _i3.Future<_i5.Result<void>>);

  @override
  _i3.Future<void> sendScreenFrame(
    _i7.Uint8List? jpegBytes, {
    required Map<String, String>? attributes,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #sendScreenFrame,
              [jpegBytes],
              {#attributes: attributes},
            ),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);

  @override
  _i3.Future<void> sendOcrContext(String? text) =>
      (super.noSuchMethod(
            Invocation.method(#sendOcrContext, [text]),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);

  @override
  _i3.Future<void> close() =>
      (super.noSuchMethod(
            Invocation.method(#close, []),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);

  @override
  _i3.Future<void> dispose() =>
      (super.noSuchMethod(
            Invocation.method(#dispose, []),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);
}

/// A class which mocks [ChatRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockChatRepository extends _i1.Mock implements _i8.ChatRepository {
  @override
  _i3.Future<_i5.Result<List<_i9.ChatSession>>> loadMainSessions({
    required String? userId,
    int? limit = 25,
    int? offset = 0,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#loadMainSessions, [], {
              #userId: userId,
              #limit: limit,
              #offset: offset,
            }),
            returnValue: _i3.Future<_i5.Result<List<_i9.ChatSession>>>.value(
              _i6.dummyValue<_i5.Result<List<_i9.ChatSession>>>(
                this,
                Invocation.method(#loadMainSessions, [], {
                  #userId: userId,
                  #limit: limit,
                  #offset: offset,
                }),
              ),
            ),
            returnValueForMissingStub:
                _i3.Future<_i5.Result<List<_i9.ChatSession>>>.value(
                  _i6.dummyValue<_i5.Result<List<_i9.ChatSession>>>(
                    this,
                    Invocation.method(#loadMainSessions, [], {
                      #userId: userId,
                      #limit: limit,
                      #offset: offset,
                    }),
                  ),
                ),
          )
          as _i3.Future<_i5.Result<List<_i9.ChatSession>>>);

  @override
  _i3.Future<_i9.ChatSession?> getMostRecentSessionForAgent({
    required String? userId,
    required String? agentId,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#getMostRecentSessionForAgent, [], {
              #userId: userId,
              #agentId: agentId,
            }),
            returnValue: _i3.Future<_i9.ChatSession?>.value(),
            returnValueForMissingStub: _i3.Future<_i9.ChatSession?>.value(),
          )
          as _i3.Future<_i9.ChatSession?>);

  @override
  _i3.Future<_i5.Result<List<_i9.ChatSession>>> getSessionsForAgent({
    required String? userId,
    required String? agentId,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#getSessionsForAgent, [], {
              #userId: userId,
              #agentId: agentId,
            }),
            returnValue: _i3.Future<_i5.Result<List<_i9.ChatSession>>>.value(
              _i6.dummyValue<_i5.Result<List<_i9.ChatSession>>>(
                this,
                Invocation.method(#getSessionsForAgent, [], {
                  #userId: userId,
                  #agentId: agentId,
                }),
              ),
            ),
            returnValueForMissingStub:
                _i3.Future<_i5.Result<List<_i9.ChatSession>>>.value(
                  _i6.dummyValue<_i5.Result<List<_i9.ChatSession>>>(
                    this,
                    Invocation.method(#getSessionsForAgent, [], {
                      #userId: userId,
                      #agentId: agentId,
                    }),
                  ),
                ),
          )
          as _i3.Future<_i5.Result<List<_i9.ChatSession>>>);

  @override
  _i3.Future<String> getOrCreateAgentSession({
    required String? userId,
    required String? agentId,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#getOrCreateAgentSession, [], {
              #userId: userId,
              #agentId: agentId,
            }),
            returnValue: _i3.Future<String>.value(
              _i6.dummyValue<String>(
                this,
                Invocation.method(#getOrCreateAgentSession, [], {
                  #userId: userId,
                  #agentId: agentId,
                }),
              ),
            ),
            returnValueForMissingStub: _i3.Future<String>.value(
              _i6.dummyValue<String>(
                this,
                Invocation.method(#getOrCreateAgentSession, [], {
                  #userId: userId,
                  #agentId: agentId,
                }),
              ),
            ),
          )
          as _i3.Future<String>);

  @override
  _i3.Future<String> createSession({
    required String? userId,
    String? agentId,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#createSession, [], {
              #userId: userId,
              #agentId: agentId,
            }),
            returnValue: _i3.Future<String>.value(
              _i6.dummyValue<String>(
                this,
                Invocation.method(#createSession, [], {
                  #userId: userId,
                  #agentId: agentId,
                }),
              ),
            ),
            returnValueForMissingStub: _i3.Future<String>.value(
              _i6.dummyValue<String>(
                this,
                Invocation.method(#createSession, [], {
                  #userId: userId,
                  #agentId: agentId,
                }),
              ),
            ),
          )
          as _i3.Future<String>);

  @override
  _i3.Future<_i5.Result<List<_i9.ChatSession>>> loadRecentSessions({
    int? limit = 10,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#loadRecentSessions, [], {#limit: limit}),
            returnValue: _i3.Future<_i5.Result<List<_i9.ChatSession>>>.value(
              _i6.dummyValue<_i5.Result<List<_i9.ChatSession>>>(
                this,
                Invocation.method(#loadRecentSessions, [], {#limit: limit}),
              ),
            ),
            returnValueForMissingStub:
                _i3.Future<_i5.Result<List<_i9.ChatSession>>>.value(
                  _i6.dummyValue<_i5.Result<List<_i9.ChatSession>>>(
                    this,
                    Invocation.method(#loadRecentSessions, [], {#limit: limit}),
                  ),
                ),
          )
          as _i3.Future<_i5.Result<List<_i9.ChatSession>>>);

  @override
  _i3.Future<_i5.Result<void>> deleteSession(String? sessionId) =>
      (super.noSuchMethod(
            Invocation.method(#deleteSession, [sessionId]),
            returnValue: _i3.Future<_i5.Result<void>>.value(
              _i6.dummyValue<_i5.Result<void>>(
                this,
                Invocation.method(#deleteSession, [sessionId]),
              ),
            ),
            returnValueForMissingStub: _i3.Future<_i5.Result<void>>.value(
              _i6.dummyValue<_i5.Result<void>>(
                this,
                Invocation.method(#deleteSession, [sessionId]),
              ),
            ),
          )
          as _i3.Future<_i5.Result<void>>);

  @override
  _i3.Future<_i5.Result<void>> saveMessage(
    _i10.ChatMessageModel? msg, {
    String? userId,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#saveMessage, [msg], {#userId: userId}),
            returnValue: _i3.Future<_i5.Result<void>>.value(
              _i6.dummyValue<_i5.Result<void>>(
                this,
                Invocation.method(#saveMessage, [msg], {#userId: userId}),
              ),
            ),
            returnValueForMissingStub: _i3.Future<_i5.Result<void>>.value(
              _i6.dummyValue<_i5.Result<void>>(
                this,
                Invocation.method(#saveMessage, [msg], {#userId: userId}),
              ),
            ),
          )
          as _i3.Future<_i5.Result<void>>);

  @override
  _i3.Future<_i5.Result<List<_i10.ChatMessageModel>>> loadMessages(
    String? sessionId, {
    int? limit = 200,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#loadMessages, [sessionId], {#limit: limit}),
            returnValue:
                _i3.Future<_i5.Result<List<_i10.ChatMessageModel>>>.value(
                  _i6.dummyValue<_i5.Result<List<_i10.ChatMessageModel>>>(
                    this,
                    Invocation.method(
                      #loadMessages,
                      [sessionId],
                      {#limit: limit},
                    ),
                  ),
                ),
            returnValueForMissingStub:
                _i3.Future<_i5.Result<List<_i10.ChatMessageModel>>>.value(
                  _i6.dummyValue<_i5.Result<List<_i10.ChatMessageModel>>>(
                    this,
                    Invocation.method(
                      #loadMessages,
                      [sessionId],
                      {#limit: limit},
                    ),
                  ),
                ),
          )
          as _i3.Future<_i5.Result<List<_i10.ChatMessageModel>>>);

  @override
  _i3.Future<_i5.Result<void>> setSessionTitle(
    String? sessionId,
    String? title, {
    String? userId,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #setSessionTitle,
              [sessionId, title],
              {#userId: userId},
            ),
            returnValue: _i3.Future<_i5.Result<void>>.value(
              _i6.dummyValue<_i5.Result<void>>(
                this,
                Invocation.method(
                  #setSessionTitle,
                  [sessionId, title],
                  {#userId: userId},
                ),
              ),
            ),
            returnValueForMissingStub: _i3.Future<_i5.Result<void>>.value(
              _i6.dummyValue<_i5.Result<void>>(
                this,
                Invocation.method(
                  #setSessionTitle,
                  [sessionId, title],
                  {#userId: userId},
                ),
              ),
            ),
          )
          as _i3.Future<_i5.Result<void>>);

  @override
  _i3.Future<_i5.Result<void>> updateFeedback(
    String? messageId,
    _i10.MessageFeedback? feedback,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#updateFeedback, [messageId, feedback]),
            returnValue: _i3.Future<_i5.Result<void>>.value(
              _i6.dummyValue<_i5.Result<void>>(
                this,
                Invocation.method(#updateFeedback, [messageId, feedback]),
              ),
            ),
            returnValueForMissingStub: _i3.Future<_i5.Result<void>>.value(
              _i6.dummyValue<_i5.Result<void>>(
                this,
                Invocation.method(#updateFeedback, [messageId, feedback]),
              ),
            ),
          )
          as _i3.Future<_i5.Result<void>>);

  @override
  _i3.Future<_i5.Result<void>> updateMessageStatus(
    String? messageId,
    _i10.MessageStatus? status, {
    String? errorReason,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #updateMessageStatus,
              [messageId, status],
              {#errorReason: errorReason},
            ),
            returnValue: _i3.Future<_i5.Result<void>>.value(
              _i6.dummyValue<_i5.Result<void>>(
                this,
                Invocation.method(
                  #updateMessageStatus,
                  [messageId, status],
                  {#errorReason: errorReason},
                ),
              ),
            ),
            returnValueForMissingStub: _i3.Future<_i5.Result<void>>.value(
              _i6.dummyValue<_i5.Result<void>>(
                this,
                Invocation.method(
                  #updateMessageStatus,
                  [messageId, status],
                  {#errorReason: errorReason},
                ),
              ),
            ),
          )
          as _i3.Future<_i5.Result<void>>);

  @override
  _i3.Future<_i5.Result<void>> deleteMessage(String? messageId) =>
      (super.noSuchMethod(
            Invocation.method(#deleteMessage, [messageId]),
            returnValue: _i3.Future<_i5.Result<void>>.value(
              _i6.dummyValue<_i5.Result<void>>(
                this,
                Invocation.method(#deleteMessage, [messageId]),
              ),
            ),
            returnValueForMissingStub: _i3.Future<_i5.Result<void>>.value(
              _i6.dummyValue<_i5.Result<void>>(
                this,
                Invocation.method(#deleteMessage, [messageId]),
              ),
            ),
          )
          as _i3.Future<_i5.Result<void>>);

  @override
  _i3.Future<_i5.Result<void>> deleteMessagesAfter(
    String? sessionId,
    int? afterSequence,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#deleteMessagesAfter, [sessionId, afterSequence]),
            returnValue: _i3.Future<_i5.Result<void>>.value(
              _i6.dummyValue<_i5.Result<void>>(
                this,
                Invocation.method(#deleteMessagesAfter, [
                  sessionId,
                  afterSequence,
                ]),
              ),
            ),
            returnValueForMissingStub: _i3.Future<_i5.Result<void>>.value(
              _i6.dummyValue<_i5.Result<void>>(
                this,
                Invocation.method(#deleteMessagesAfter, [
                  sessionId,
                  afterSequence,
                ]),
              ),
            ),
          )
          as _i3.Future<_i5.Result<void>>);

  @override
  _i3.Future<_i5.Result<void>> updateMessageContent(
    String? messageId,
    String? newContent,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#updateMessageContent, [messageId, newContent]),
            returnValue: _i3.Future<_i5.Result<void>>.value(
              _i6.dummyValue<_i5.Result<void>>(
                this,
                Invocation.method(#updateMessageContent, [
                  messageId,
                  newContent,
                ]),
              ),
            ),
            returnValueForMissingStub: _i3.Future<_i5.Result<void>>.value(
              _i6.dummyValue<_i5.Result<void>>(
                this,
                Invocation.method(#updateMessageContent, [
                  messageId,
                  newContent,
                ]),
              ),
            ),
          )
          as _i3.Future<_i5.Result<void>>);

  @override
  _i3.Future<int?> getMessageSequence(String? messageId) =>
      (super.noSuchMethod(
            Invocation.method(#getMessageSequence, [messageId]),
            returnValue: _i3.Future<int?>.value(),
            returnValueForMissingStub: _i3.Future<int?>.value(),
          )
          as _i3.Future<int?>);
}
