// Mocks generated by Mockito 5.4.6 from annotations
// in aura/test/viewmodels/link_device_viewmodel_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i5;
import 'dart:typed_data' as _i11;

import 'package:aura/core/network/api_response.dart' as _i7;
import 'package:aura/data/models/chat_attachment.dart' as _i9;
import 'package:aura/data/models/daily_briefing.dart' as _i10;
import 'package:aura/data/services/backend_api_service.dart' as _i6;
import 'package:cloud_firestore/cloud_firestore.dart' as _i4;
import 'package:cloud_firestore_platform_interface/cloud_firestore_platform_interface.dart'
    as _i3;
import 'package:firebase_core/firebase_core.dart' as _i2;
import 'package:mockito/mockito.dart' as _i1;
import 'package:mockito/src/dummies.dart' as _i8;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

class _FakeFirebaseApp_0 extends _i1.SmartFake implements _i2.FirebaseApp {
  _FakeFirebaseApp_0(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeSettings_1 extends _i1.SmartFake implements _i3.Settings {
  _FakeSettings_1(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeCollectionReference_2<T extends Object?> extends _i1.SmartFake
    implements _i4.CollectionReference<T> {
  _FakeCollectionReference_2(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeWriteBatch_3 extends _i1.SmartFake implements _i4.WriteBatch {
  _FakeWriteBatch_3(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeLoadBundleTask_4 extends _i1.SmartFake
    implements _i4.LoadBundleTask {
  _FakeLoadBundleTask_4(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeQuerySnapshot_5<T1 extends Object?> extends _i1.SmartFake
    implements _i4.QuerySnapshot<T1> {
  _FakeQuerySnapshot_5(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeQuery_6<T extends Object?> extends _i1.SmartFake
    implements _i4.Query<T> {
  _FakeQuery_6(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeDocumentReference_7<T extends Object?> extends _i1.SmartFake
    implements _i4.DocumentReference<T> {
  _FakeDocumentReference_7(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeFuture_8<T1> extends _i1.SmartFake implements _i5.Future<T1> {
  _FakeFuture_8(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakePipelineSource_9 extends _i1.SmartFake
    implements _i4.PipelineSource {
  _FakePipelineSource_9(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

/// A class which mocks [BackendApiService].
///
/// See the documentation for Mockito's code generation for more information.
class MockBackendApiService extends _i1.Mock implements _i6.BackendApiService {
  @override
  _i5.Future<_i7.Result<_i6.ChatResponse>> sendMessage(
    String? message,
    String? userId, {
    List<Map<String, dynamic>>? history = const [],
    String? sessionId,
    String? clientMessageId,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #sendMessage,
              [message, userId],
              {
                #history: history,
                #sessionId: sessionId,
                #clientMessageId: clientMessageId,
              },
            ),
            returnValue: _i5.Future<_i7.Result<_i6.ChatResponse>>.value(
              _i8.dummyValue<_i7.Result<_i6.ChatResponse>>(
                this,
                Invocation.method(
                  #sendMessage,
                  [message, userId],
                  {
                    #history: history,
                    #sessionId: sessionId,
                    #clientMessageId: clientMessageId,
                  },
                ),
              ),
            ),
            returnValueForMissingStub:
                _i5.Future<_i7.Result<_i6.ChatResponse>>.value(
                  _i8.dummyValue<_i7.Result<_i6.ChatResponse>>(
                    this,
                    Invocation.method(
                      #sendMessage,
                      [message, userId],
                      {
                        #history: history,
                        #sessionId: sessionId,
                        #clientMessageId: clientMessageId,
                      },
                    ),
                  ),
                ),
          )
          as _i5.Future<_i7.Result<_i6.ChatResponse>>);

  @override
  _i5.Stream<_i6.ChatStreamEvent> sendMessageStream(
    String? message,
    String? userId, {
    List<Map<String, dynamic>>? history = const [],
    String? sessionId,
    String? clientMessageId,
    String? agentId,
    List<_i9.ChatAttachment>? attachments,
    String? notificationReason,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #sendMessageStream,
              [message, userId],
              {
                #history: history,
                #sessionId: sessionId,
                #clientMessageId: clientMessageId,
                #agentId: agentId,
                #attachments: attachments,
                #notificationReason: notificationReason,
              },
            ),
            returnValue: _i5.Stream<_i6.ChatStreamEvent>.empty(),
            returnValueForMissingStub: _i5.Stream<_i6.ChatStreamEvent>.empty(),
          )
          as _i5.Stream<_i6.ChatStreamEvent>);

  @override
  _i5.Future<void> markEngagementResponded(String? engagementId) =>
      (super.noSuchMethod(
            Invocation.method(#markEngagementResponded, [engagementId]),
            returnValue: _i5.Future<void>.value(),
            returnValueForMissingStub: _i5.Future<void>.value(),
          )
          as _i5.Future<void>);

  @override
  _i5.Future<_i7.Result<void>> deleteAccount() =>
      (super.noSuchMethod(
            Invocation.method(#deleteAccount, []),
            returnValue: _i5.Future<_i7.Result<void>>.value(
              _i8.dummyValue<_i7.Result<void>>(
                this,
                Invocation.method(#deleteAccount, []),
              ),
            ),
            returnValueForMissingStub: _i5.Future<_i7.Result<void>>.value(
              _i8.dummyValue<_i7.Result<void>>(
                this,
                Invocation.method(#deleteAccount, []),
              ),
            ),
          )
          as _i5.Future<_i7.Result<void>>);

  @override
  _i5.Future<_i7.Result<void>> revokeAuraMemory() =>
      (super.noSuchMethod(
            Invocation.method(#revokeAuraMemory, []),
            returnValue: _i5.Future<_i7.Result<void>>.value(
              _i8.dummyValue<_i7.Result<void>>(
                this,
                Invocation.method(#revokeAuraMemory, []),
              ),
            ),
            returnValueForMissingStub: _i5.Future<_i7.Result<void>>.value(
              _i8.dummyValue<_i7.Result<void>>(
                this,
                Invocation.method(#revokeAuraMemory, []),
              ),
            ),
          )
          as _i5.Future<_i7.Result<void>>);

  @override
  _i5.Future<_i7.Result<Map<String, dynamic>>> refreshBuddyPills() =>
      (super.noSuchMethod(
            Invocation.method(#refreshBuddyPills, []),
            returnValue: _i5.Future<_i7.Result<Map<String, dynamic>>>.value(
              _i8.dummyValue<_i7.Result<Map<String, dynamic>>>(
                this,
                Invocation.method(#refreshBuddyPills, []),
              ),
            ),
            returnValueForMissingStub:
                _i5.Future<_i7.Result<Map<String, dynamic>>>.value(
                  _i8.dummyValue<_i7.Result<Map<String, dynamic>>>(
                    this,
                    Invocation.method(#refreshBuddyPills, []),
                  ),
                ),
          )
          as _i5.Future<_i7.Result<Map<String, dynamic>>>);

  @override
  _i5.Future<_i7.Result<Map<String, dynamic>>> startDevicePairing() =>
      (super.noSuchMethod(
            Invocation.method(#startDevicePairing, []),
            returnValue: _i5.Future<_i7.Result<Map<String, dynamic>>>.value(
              _i8.dummyValue<_i7.Result<Map<String, dynamic>>>(
                this,
                Invocation.method(#startDevicePairing, []),
              ),
            ),
            returnValueForMissingStub:
                _i5.Future<_i7.Result<Map<String, dynamic>>>.value(
                  _i8.dummyValue<_i7.Result<Map<String, dynamic>>>(
                    this,
                    Invocation.method(#startDevicePairing, []),
                  ),
                ),
          )
          as _i5.Future<_i7.Result<Map<String, dynamic>>>);

  @override
  _i5.Future<_i7.Result<Map<String, dynamic>>> unlinkDevice(String? deviceId) =>
      (super.noSuchMethod(
            Invocation.method(#unlinkDevice, [deviceId]),
            returnValue: _i5.Future<_i7.Result<Map<String, dynamic>>>.value(
              _i8.dummyValue<_i7.Result<Map<String, dynamic>>>(
                this,
                Invocation.method(#unlinkDevice, [deviceId]),
              ),
            ),
            returnValueForMissingStub:
                _i5.Future<_i7.Result<Map<String, dynamic>>>.value(
                  _i8.dummyValue<_i7.Result<Map<String, dynamic>>>(
                    this,
                    Invocation.method(#unlinkDevice, [deviceId]),
                  ),
                ),
          )
          as _i5.Future<_i7.Result<Map<String, dynamic>>>);

  @override
  _i5.Future<_i7.Result<Map<String, dynamic>>> consolidateSession({
    required String? sessionId,
    required List<Map<String, dynamic>>? turns,
    String? modality = 'text',
  }) =>
      (super.noSuchMethod(
            Invocation.method(#consolidateSession, [], {
              #sessionId: sessionId,
              #turns: turns,
              #modality: modality,
            }),
            returnValue: _i5.Future<_i7.Result<Map<String, dynamic>>>.value(
              _i8.dummyValue<_i7.Result<Map<String, dynamic>>>(
                this,
                Invocation.method(#consolidateSession, [], {
                  #sessionId: sessionId,
                  #turns: turns,
                  #modality: modality,
                }),
              ),
            ),
            returnValueForMissingStub:
                _i5.Future<_i7.Result<Map<String, dynamic>>>.value(
                  _i8.dummyValue<_i7.Result<Map<String, dynamic>>>(
                    this,
                    Invocation.method(#consolidateSession, [], {
                      #sessionId: sessionId,
                      #turns: turns,
                      #modality: modality,
                    }),
                  ),
                ),
          )
          as _i5.Future<_i7.Result<Map<String, dynamic>>>);

  @override
  _i5.Future<_i7.Result<Map<String, dynamic>>> seedOnboardingInterests(
    List<String>? interestSlugs,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#seedOnboardingInterests, [interestSlugs]),
            returnValue: _i5.Future<_i7.Result<Map<String, dynamic>>>.value(
              _i8.dummyValue<_i7.Result<Map<String, dynamic>>>(
                this,
                Invocation.method(#seedOnboardingInterests, [interestSlugs]),
              ),
            ),
            returnValueForMissingStub:
                _i5.Future<_i7.Result<Map<String, dynamic>>>.value(
                  _i8.dummyValue<_i7.Result<Map<String, dynamic>>>(
                    this,
                    Invocation.method(#seedOnboardingInterests, [
                      interestSlugs,
                    ]),
                  ),
                ),
          )
          as _i5.Future<_i7.Result<Map<String, dynamic>>>);

  @override
  _i5.Future<_i7.Result<Map<String, dynamic>>> postSignalEvents(
    List<Map<String, dynamic>>? events,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#postSignalEvents, [events]),
            returnValue: _i5.Future<_i7.Result<Map<String, dynamic>>>.value(
              _i8.dummyValue<_i7.Result<Map<String, dynamic>>>(
                this,
                Invocation.method(#postSignalEvents, [events]),
              ),
            ),
            returnValueForMissingStub:
                _i5.Future<_i7.Result<Map<String, dynamic>>>.value(
                  _i8.dummyValue<_i7.Result<Map<String, dynamic>>>(
                    this,
                    Invocation.method(#postSignalEvents, [events]),
                  ),
                ),
          )
          as _i5.Future<_i7.Result<Map<String, dynamic>>>);

  @override
  _i5.Future<List<Map<String, dynamic>>> fetchThreadMessages(
    String? threadId,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#fetchThreadMessages, [threadId]),
            returnValue: _i5.Future<List<Map<String, dynamic>>>.value(
              <Map<String, dynamic>>[],
            ),
            returnValueForMissingStub:
                _i5.Future<List<Map<String, dynamic>>>.value(
                  <Map<String, dynamic>>[],
                ),
          )
          as _i5.Future<List<Map<String, dynamic>>>);

  @override
  _i5.Future<_i10.DailyBriefing?> fetchTodayBriefing() =>
      (super.noSuchMethod(
            Invocation.method(#fetchTodayBriefing, []),
            returnValue: _i5.Future<_i10.DailyBriefing?>.value(),
            returnValueForMissingStub: _i5.Future<_i10.DailyBriefing?>.value(),
          )
          as _i5.Future<_i10.DailyBriefing?>);

  @override
  _i5.Future<_i10.DailyBriefing?> generateTodayBriefing({
    bool? force = false,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#generateTodayBriefing, [], {#force: force}),
            returnValue: _i5.Future<_i10.DailyBriefing?>.value(),
            returnValueForMissingStub: _i5.Future<_i10.DailyBriefing?>.value(),
          )
          as _i5.Future<_i10.DailyBriefing?>);

  @override
  _i5.Future<_i10.DailyBriefing?> fetchWorldBriefing({bool? refresh = false}) =>
      (super.noSuchMethod(
            Invocation.method(#fetchWorldBriefing, [], {#refresh: refresh}),
            returnValue: _i5.Future<_i10.DailyBriefing?>.value(),
            returnValueForMissingStub: _i5.Future<_i10.DailyBriefing?>.value(),
          )
          as _i5.Future<_i10.DailyBriefing?>);
}

/// A class which mocks [FirebaseFirestore].
///
/// See the documentation for Mockito's code generation for more information.
class MockFirebaseFirestore extends _i1.Mock implements _i4.FirebaseFirestore {
  @override
  _i2.FirebaseApp get app =>
      (super.noSuchMethod(
            Invocation.getter(#app),
            returnValue: _FakeFirebaseApp_0(this, Invocation.getter(#app)),
            returnValueForMissingStub: _FakeFirebaseApp_0(
              this,
              Invocation.getter(#app),
            ),
          )
          as _i2.FirebaseApp);

  @override
  String get databaseId =>
      (super.noSuchMethod(
            Invocation.getter(#databaseId),
            returnValue: _i8.dummyValue<String>(
              this,
              Invocation.getter(#databaseId),
            ),
            returnValueForMissingStub: _i8.dummyValue<String>(
              this,
              Invocation.getter(#databaseId),
            ),
          )
          as String);

  @override
  _i3.Settings get settings =>
      (super.noSuchMethod(
            Invocation.getter(#settings),
            returnValue: _FakeSettings_1(this, Invocation.getter(#settings)),
            returnValueForMissingStub: _FakeSettings_1(
              this,
              Invocation.getter(#settings),
            ),
          )
          as _i3.Settings);

  @override
  set app(_i2.FirebaseApp? value) => super.noSuchMethod(
    Invocation.setter(#app, value),
    returnValueForMissingStub: null,
  );

  @override
  set databaseId(String? value) => super.noSuchMethod(
    Invocation.setter(#databaseId, value),
    returnValueForMissingStub: null,
  );

  @override
  set settings(_i3.Settings? settings) => super.noSuchMethod(
    Invocation.setter(#settings, settings),
    returnValueForMissingStub: null,
  );

  @override
  Map<dynamic, dynamic> get pluginConstants =>
      (super.noSuchMethod(
            Invocation.getter(#pluginConstants),
            returnValue: <dynamic, dynamic>{},
            returnValueForMissingStub: <dynamic, dynamic>{},
          )
          as Map<dynamic, dynamic>);

  @override
  _i4.CollectionReference<Map<String, dynamic>> collection(
    String? collectionPath,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#collection, [collectionPath]),
            returnValue: _FakeCollectionReference_2<Map<String, dynamic>>(
              this,
              Invocation.method(#collection, [collectionPath]),
            ),
            returnValueForMissingStub:
                _FakeCollectionReference_2<Map<String, dynamic>>(
                  this,
                  Invocation.method(#collection, [collectionPath]),
                ),
          )
          as _i4.CollectionReference<Map<String, dynamic>>);

  @override
  _i4.WriteBatch batch() =>
      (super.noSuchMethod(
            Invocation.method(#batch, []),
            returnValue: _FakeWriteBatch_3(this, Invocation.method(#batch, [])),
            returnValueForMissingStub: _FakeWriteBatch_3(
              this,
              Invocation.method(#batch, []),
            ),
          )
          as _i4.WriteBatch);

  @override
  _i5.Future<void> clearPersistence() =>
      (super.noSuchMethod(
            Invocation.method(#clearPersistence, []),
            returnValue: _i5.Future<void>.value(),
            returnValueForMissingStub: _i5.Future<void>.value(),
          )
          as _i5.Future<void>);

  @override
  _i4.LoadBundleTask loadBundle(_i11.Uint8List? bundle) =>
      (super.noSuchMethod(
            Invocation.method(#loadBundle, [bundle]),
            returnValue: _FakeLoadBundleTask_4(
              this,
              Invocation.method(#loadBundle, [bundle]),
            ),
            returnValueForMissingStub: _FakeLoadBundleTask_4(
              this,
              Invocation.method(#loadBundle, [bundle]),
            ),
          )
          as _i4.LoadBundleTask);

  @override
  void useFirestoreEmulator(
    String? host,
    int? port, {
    bool? sslEnabled = false,
    bool? automaticHostMapping = true,
  }) => super.noSuchMethod(
    Invocation.method(
      #useFirestoreEmulator,
      [host, port],
      {#sslEnabled: sslEnabled, #automaticHostMapping: automaticHostMapping},
    ),
    returnValueForMissingStub: null,
  );

  @override
  _i5.Future<_i4.QuerySnapshot<T>> namedQueryWithConverterGet<T>(
    String? name, {
    _i3.GetOptions? options = const _i3.GetOptions(),
    required _i4.FromFirestore<T>? fromFirestore,
    required _i4.ToFirestore<T>? toFirestore,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #namedQueryWithConverterGet,
              [name],
              {
                #options: options,
                #fromFirestore: fromFirestore,
                #toFirestore: toFirestore,
              },
            ),
            returnValue: _i5.Future<_i4.QuerySnapshot<T>>.value(
              _FakeQuerySnapshot_5<T>(
                this,
                Invocation.method(
                  #namedQueryWithConverterGet,
                  [name],
                  {
                    #options: options,
                    #fromFirestore: fromFirestore,
                    #toFirestore: toFirestore,
                  },
                ),
              ),
            ),
            returnValueForMissingStub: _i5.Future<_i4.QuerySnapshot<T>>.value(
              _FakeQuerySnapshot_5<T>(
                this,
                Invocation.method(
                  #namedQueryWithConverterGet,
                  [name],
                  {
                    #options: options,
                    #fromFirestore: fromFirestore,
                    #toFirestore: toFirestore,
                  },
                ),
              ),
            ),
          )
          as _i5.Future<_i4.QuerySnapshot<T>>);

  @override
  _i5.Future<_i4.QuerySnapshot<Map<String, dynamic>>> namedQueryGet(
    String? name, {
    _i3.GetOptions? options = const _i3.GetOptions(),
  }) =>
      (super.noSuchMethod(
            Invocation.method(#namedQueryGet, [name], {#options: options}),
            returnValue:
                _i5.Future<_i4.QuerySnapshot<Map<String, dynamic>>>.value(
                  _FakeQuerySnapshot_5<Map<String, dynamic>>(
                    this,
                    Invocation.method(
                      #namedQueryGet,
                      [name],
                      {#options: options},
                    ),
                  ),
                ),
            returnValueForMissingStub:
                _i5.Future<_i4.QuerySnapshot<Map<String, dynamic>>>.value(
                  _FakeQuerySnapshot_5<Map<String, dynamic>>(
                    this,
                    Invocation.method(
                      #namedQueryGet,
                      [name],
                      {#options: options},
                    ),
                  ),
                ),
          )
          as _i5.Future<_i4.QuerySnapshot<Map<String, dynamic>>>);

  @override
  _i4.Query<Map<String, dynamic>> collectionGroup(String? collectionPath) =>
      (super.noSuchMethod(
            Invocation.method(#collectionGroup, [collectionPath]),
            returnValue: _FakeQuery_6<Map<String, dynamic>>(
              this,
              Invocation.method(#collectionGroup, [collectionPath]),
            ),
            returnValueForMissingStub: _FakeQuery_6<Map<String, dynamic>>(
              this,
              Invocation.method(#collectionGroup, [collectionPath]),
            ),
          )
          as _i4.Query<Map<String, dynamic>>);

  @override
  _i5.Future<void> disableNetwork() =>
      (super.noSuchMethod(
            Invocation.method(#disableNetwork, []),
            returnValue: _i5.Future<void>.value(),
            returnValueForMissingStub: _i5.Future<void>.value(),
          )
          as _i5.Future<void>);

  @override
  _i4.DocumentReference<Map<String, dynamic>> doc(String? documentPath) =>
      (super.noSuchMethod(
            Invocation.method(#doc, [documentPath]),
            returnValue: _FakeDocumentReference_7<Map<String, dynamic>>(
              this,
              Invocation.method(#doc, [documentPath]),
            ),
            returnValueForMissingStub:
                _FakeDocumentReference_7<Map<String, dynamic>>(
                  this,
                  Invocation.method(#doc, [documentPath]),
                ),
          )
          as _i4.DocumentReference<Map<String, dynamic>>);

  @override
  _i5.Future<void> enableNetwork() =>
      (super.noSuchMethod(
            Invocation.method(#enableNetwork, []),
            returnValue: _i5.Future<void>.value(),
            returnValueForMissingStub: _i5.Future<void>.value(),
          )
          as _i5.Future<void>);

  @override
  _i5.Stream<void> snapshotsInSync() =>
      (super.noSuchMethod(
            Invocation.method(#snapshotsInSync, []),
            returnValue: _i5.Stream<void>.empty(),
            returnValueForMissingStub: _i5.Stream<void>.empty(),
          )
          as _i5.Stream<void>);

  @override
  _i5.Future<T> runTransaction<T>(
    _i4.TransactionHandler<T>? transactionHandler, {
    Duration? timeout = const Duration(seconds: 30),
    int? maxAttempts = 5,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #runTransaction,
              [transactionHandler],
              {#timeout: timeout, #maxAttempts: maxAttempts},
            ),
            returnValue:
                _i8.ifNotNull(
                  _i8.dummyValueOrNull<T>(
                    this,
                    Invocation.method(
                      #runTransaction,
                      [transactionHandler],
                      {#timeout: timeout, #maxAttempts: maxAttempts},
                    ),
                  ),
                  (T v) => _i5.Future<T>.value(v),
                ) ??
                _FakeFuture_8<T>(
                  this,
                  Invocation.method(
                    #runTransaction,
                    [transactionHandler],
                    {#timeout: timeout, #maxAttempts: maxAttempts},
                  ),
                ),
            returnValueForMissingStub:
                _i8.ifNotNull(
                  _i8.dummyValueOrNull<T>(
                    this,
                    Invocation.method(
                      #runTransaction,
                      [transactionHandler],
                      {#timeout: timeout, #maxAttempts: maxAttempts},
                    ),
                  ),
                  (T v) => _i5.Future<T>.value(v),
                ) ??
                _FakeFuture_8<T>(
                  this,
                  Invocation.method(
                    #runTransaction,
                    [transactionHandler],
                    {#timeout: timeout, #maxAttempts: maxAttempts},
                  ),
                ),
          )
          as _i5.Future<T>);

  @override
  _i5.Future<void> terminate() =>
      (super.noSuchMethod(
            Invocation.method(#terminate, []),
            returnValue: _i5.Future<void>.value(),
            returnValueForMissingStub: _i5.Future<void>.value(),
          )
          as _i5.Future<void>);

  @override
  _i5.Future<void> waitForPendingWrites() =>
      (super.noSuchMethod(
            Invocation.method(#waitForPendingWrites, []),
            returnValue: _i5.Future<void>.value(),
            returnValueForMissingStub: _i5.Future<void>.value(),
          )
          as _i5.Future<void>);

  @override
  _i4.PipelineSource pipeline() =>
      (super.noSuchMethod(
            Invocation.method(#pipeline, []),
            returnValue: _FakePipelineSource_9(
              this,
              Invocation.method(#pipeline, []),
            ),
            returnValueForMissingStub: _FakePipelineSource_9(
              this,
              Invocation.method(#pipeline, []),
            ),
          )
          as _i4.PipelineSource);

  @override
  _i5.Future<void> setIndexConfigurationFromJSON(String? json) =>
      (super.noSuchMethod(
            Invocation.method(#setIndexConfigurationFromJSON, [json]),
            returnValue: _i5.Future<void>.value(),
            returnValueForMissingStub: _i5.Future<void>.value(),
          )
          as _i5.Future<void>);
}
