// Mocks generated by Mockito 5.4.6 from annotations
// in aura/test/viewmodels/text_chat_viewmodel_send_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i3;

import 'package:aura/core/network/api_response.dart' as _i8;
import 'package:aura/core/network/connectivity_service.dart' as _i6;
import 'package:aura/data/local/app_database.dart' as _i9;
import 'package:aura/data/models/chat_attachment.dart' as _i5;
import 'package:aura/data/models/chat_message_model.dart' as _i11;
import 'package:aura/data/repositories/chat_repository.dart' as _i7;
import 'package:aura/data/services/backend_api_service.dart' as _i4;
import 'package:aura/data/services/chat_backup_service.dart' as _i12;
import 'package:aura/data/services/chat_service_provider.dart' as _i2;
import 'package:aura/data/services/chat_session_manager.dart' as _i14;
import 'package:aura/data/services/feedback_service.dart' as _i13;
import 'package:aura/data/services/posthog_analytics_service.dart' as _i15;
import 'package:mockito/mockito.dart' as _i1;
import 'package:mockito/src/dummies.dart' as _i10;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

/// A class which mocks [ChatServiceProvider].
///
/// See the documentation for Mockito's code generation for more information.
class MockChatServiceProvider extends _i1.Mock
    implements _i2.ChatServiceProvider {
  @override
  _i3.Stream<_i4.ChatStreamEvent> sendMessageStream(
    String? message,
    String? userId, {
    List<Map<String, dynamic>>? history = const [],
    String? sessionId,
    String? clientMessageId,
    String? agentId,
    List<_i5.ChatAttachment>? attachments,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #sendMessageStream,
              [message, userId],
              {
                #history: history,
                #sessionId: sessionId,
                #clientMessageId: clientMessageId,
                #agentId: agentId,
                #attachments: attachments,
              },
            ),
            returnValue: _i3.Stream<_i4.ChatStreamEvent>.empty(),
            returnValueForMissingStub: _i3.Stream<_i4.ChatStreamEvent>.empty(),
          )
          as _i3.Stream<_i4.ChatStreamEvent>);

  @override
  _i3.Future<void> markEngagementResponded(String? engagementId) =>
      (super.noSuchMethod(
            Invocation.method(#markEngagementResponded, [engagementId]),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);
}

/// A class which mocks [ConnectivityService].
///
/// See the documentation for Mockito's code generation for more information.
class MockConnectivityService extends _i1.Mock
    implements _i6.ConnectivityService {
  @override
  _i3.Stream<_i6.ConnectivityStatus> get statusStream =>
      (super.noSuchMethod(
            Invocation.getter(#statusStream),
            returnValue: _i3.Stream<_i6.ConnectivityStatus>.empty(),
            returnValueForMissingStub:
                _i3.Stream<_i6.ConnectivityStatus>.empty(),
          )
          as _i3.Stream<_i6.ConnectivityStatus>);

  @override
  _i3.Future<bool> get isConnected =>
      (super.noSuchMethod(
            Invocation.getter(#isConnected),
            returnValue: _i3.Future<bool>.value(false),
            returnValueForMissingStub: _i3.Future<bool>.value(false),
          )
          as _i3.Future<bool>);
}

/// A class which mocks [ChatRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockChatRepository extends _i1.Mock implements _i7.ChatRepository {
  @override
  _i3.Future<_i8.Result<List<_i9.ChatSession>>> loadMainSessions({
    required String? userId,
    int? limit = 25,
    int? offset = 0,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#loadMainSessions, [], {
              #userId: userId,
              #limit: limit,
              #offset: offset,
            }),
            returnValue: _i3.Future<_i8.Result<List<_i9.ChatSession>>>.value(
              _i10.dummyValue<_i8.Result<List<_i9.ChatSession>>>(
                this,
                Invocation.method(#loadMainSessions, [], {
                  #userId: userId,
                  #limit: limit,
                  #offset: offset,
                }),
              ),
            ),
            returnValueForMissingStub:
                _i3.Future<_i8.Result<List<_i9.ChatSession>>>.value(
                  _i10.dummyValue<_i8.Result<List<_i9.ChatSession>>>(
                    this,
                    Invocation.method(#loadMainSessions, [], {
                      #userId: userId,
                      #limit: limit,
                      #offset: offset,
                    }),
                  ),
                ),
          )
          as _i3.Future<_i8.Result<List<_i9.ChatSession>>>);

  @override
  _i3.Future<_i9.ChatSession?> getMostRecentSessionForAgent({
    required String? userId,
    required String? agentId,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#getMostRecentSessionForAgent, [], {
              #userId: userId,
              #agentId: agentId,
            }),
            returnValue: _i3.Future<_i9.ChatSession?>.value(),
            returnValueForMissingStub: _i3.Future<_i9.ChatSession?>.value(),
          )
          as _i3.Future<_i9.ChatSession?>);

  @override
  _i3.Future<_i8.Result<List<_i9.ChatSession>>> getSessionsForAgent({
    required String? userId,
    required String? agentId,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#getSessionsForAgent, [], {
              #userId: userId,
              #agentId: agentId,
            }),
            returnValue: _i3.Future<_i8.Result<List<_i9.ChatSession>>>.value(
              _i10.dummyValue<_i8.Result<List<_i9.ChatSession>>>(
                this,
                Invocation.method(#getSessionsForAgent, [], {
                  #userId: userId,
                  #agentId: agentId,
                }),
              ),
            ),
            returnValueForMissingStub:
                _i3.Future<_i8.Result<List<_i9.ChatSession>>>.value(
                  _i10.dummyValue<_i8.Result<List<_i9.ChatSession>>>(
                    this,
                    Invocation.method(#getSessionsForAgent, [], {
                      #userId: userId,
                      #agentId: agentId,
                    }),
                  ),
                ),
          )
          as _i3.Future<_i8.Result<List<_i9.ChatSession>>>);

  @override
  _i3.Future<String> getOrCreateAgentSession({
    required String? userId,
    required String? agentId,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#getOrCreateAgentSession, [], {
              #userId: userId,
              #agentId: agentId,
            }),
            returnValue: _i3.Future<String>.value(
              _i10.dummyValue<String>(
                this,
                Invocation.method(#getOrCreateAgentSession, [], {
                  #userId: userId,
                  #agentId: agentId,
                }),
              ),
            ),
            returnValueForMissingStub: _i3.Future<String>.value(
              _i10.dummyValue<String>(
                this,
                Invocation.method(#getOrCreateAgentSession, [], {
                  #userId: userId,
                  #agentId: agentId,
                }),
              ),
            ),
          )
          as _i3.Future<String>);

  @override
  _i3.Future<String> createSession({
    required String? userId,
    String? agentId,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#createSession, [], {
              #userId: userId,
              #agentId: agentId,
            }),
            returnValue: _i3.Future<String>.value(
              _i10.dummyValue<String>(
                this,
                Invocation.method(#createSession, [], {
                  #userId: userId,
                  #agentId: agentId,
                }),
              ),
            ),
            returnValueForMissingStub: _i3.Future<String>.value(
              _i10.dummyValue<String>(
                this,
                Invocation.method(#createSession, [], {
                  #userId: userId,
                  #agentId: agentId,
                }),
              ),
            ),
          )
          as _i3.Future<String>);

  @override
  _i3.Future<_i8.Result<List<_i9.ChatSession>>> loadRecentSessions({
    int? limit = 10,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#loadRecentSessions, [], {#limit: limit}),
            returnValue: _i3.Future<_i8.Result<List<_i9.ChatSession>>>.value(
              _i10.dummyValue<_i8.Result<List<_i9.ChatSession>>>(
                this,
                Invocation.method(#loadRecentSessions, [], {#limit: limit}),
              ),
            ),
            returnValueForMissingStub:
                _i3.Future<_i8.Result<List<_i9.ChatSession>>>.value(
                  _i10.dummyValue<_i8.Result<List<_i9.ChatSession>>>(
                    this,
                    Invocation.method(#loadRecentSessions, [], {#limit: limit}),
                  ),
                ),
          )
          as _i3.Future<_i8.Result<List<_i9.ChatSession>>>);

  @override
  _i3.Future<_i8.Result<void>> deleteSession(String? sessionId) =>
      (super.noSuchMethod(
            Invocation.method(#deleteSession, [sessionId]),
            returnValue: _i3.Future<_i8.Result<void>>.value(
              _i10.dummyValue<_i8.Result<void>>(
                this,
                Invocation.method(#deleteSession, [sessionId]),
              ),
            ),
            returnValueForMissingStub: _i3.Future<_i8.Result<void>>.value(
              _i10.dummyValue<_i8.Result<void>>(
                this,
                Invocation.method(#deleteSession, [sessionId]),
              ),
            ),
          )
          as _i3.Future<_i8.Result<void>>);

  @override
  _i3.Future<_i8.Result<void>> saveMessage(
    _i11.ChatMessageModel? msg, {
    String? userId,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#saveMessage, [msg], {#userId: userId}),
            returnValue: _i3.Future<_i8.Result<void>>.value(
              _i10.dummyValue<_i8.Result<void>>(
                this,
                Invocation.method(#saveMessage, [msg], {#userId: userId}),
              ),
            ),
            returnValueForMissingStub: _i3.Future<_i8.Result<void>>.value(
              _i10.dummyValue<_i8.Result<void>>(
                this,
                Invocation.method(#saveMessage, [msg], {#userId: userId}),
              ),
            ),
          )
          as _i3.Future<_i8.Result<void>>);

  @override
  _i3.Future<_i8.Result<List<_i11.ChatMessageModel>>> loadMessages(
    String? sessionId, {
    int? limit = 200,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#loadMessages, [sessionId], {#limit: limit}),
            returnValue:
                _i3.Future<_i8.Result<List<_i11.ChatMessageModel>>>.value(
                  _i10.dummyValue<_i8.Result<List<_i11.ChatMessageModel>>>(
                    this,
                    Invocation.method(
                      #loadMessages,
                      [sessionId],
                      {#limit: limit},
                    ),
                  ),
                ),
            returnValueForMissingStub:
                _i3.Future<_i8.Result<List<_i11.ChatMessageModel>>>.value(
                  _i10.dummyValue<_i8.Result<List<_i11.ChatMessageModel>>>(
                    this,
                    Invocation.method(
                      #loadMessages,
                      [sessionId],
                      {#limit: limit},
                    ),
                  ),
                ),
          )
          as _i3.Future<_i8.Result<List<_i11.ChatMessageModel>>>);

  @override
  _i3.Future<_i8.Result<void>> setSessionTitle(
    String? sessionId,
    String? title, {
    String? userId,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #setSessionTitle,
              [sessionId, title],
              {#userId: userId},
            ),
            returnValue: _i3.Future<_i8.Result<void>>.value(
              _i10.dummyValue<_i8.Result<void>>(
                this,
                Invocation.method(
                  #setSessionTitle,
                  [sessionId, title],
                  {#userId: userId},
                ),
              ),
            ),
            returnValueForMissingStub: _i3.Future<_i8.Result<void>>.value(
              _i10.dummyValue<_i8.Result<void>>(
                this,
                Invocation.method(
                  #setSessionTitle,
                  [sessionId, title],
                  {#userId: userId},
                ),
              ),
            ),
          )
          as _i3.Future<_i8.Result<void>>);

  @override
  _i3.Future<_i8.Result<void>> updateFeedback(
    String? messageId,
    _i11.MessageFeedback? feedback,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#updateFeedback, [messageId, feedback]),
            returnValue: _i3.Future<_i8.Result<void>>.value(
              _i10.dummyValue<_i8.Result<void>>(
                this,
                Invocation.method(#updateFeedback, [messageId, feedback]),
              ),
            ),
            returnValueForMissingStub: _i3.Future<_i8.Result<void>>.value(
              _i10.dummyValue<_i8.Result<void>>(
                this,
                Invocation.method(#updateFeedback, [messageId, feedback]),
              ),
            ),
          )
          as _i3.Future<_i8.Result<void>>);

  @override
  _i3.Future<_i8.Result<void>> updateMessageStatus(
    String? messageId,
    _i11.MessageStatus? status, {
    String? errorReason,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #updateMessageStatus,
              [messageId, status],
              {#errorReason: errorReason},
            ),
            returnValue: _i3.Future<_i8.Result<void>>.value(
              _i10.dummyValue<_i8.Result<void>>(
                this,
                Invocation.method(
                  #updateMessageStatus,
                  [messageId, status],
                  {#errorReason: errorReason},
                ),
              ),
            ),
            returnValueForMissingStub: _i3.Future<_i8.Result<void>>.value(
              _i10.dummyValue<_i8.Result<void>>(
                this,
                Invocation.method(
                  #updateMessageStatus,
                  [messageId, status],
                  {#errorReason: errorReason},
                ),
              ),
            ),
          )
          as _i3.Future<_i8.Result<void>>);

  @override
  _i3.Future<_i8.Result<void>> deleteMessage(String? messageId) =>
      (super.noSuchMethod(
            Invocation.method(#deleteMessage, [messageId]),
            returnValue: _i3.Future<_i8.Result<void>>.value(
              _i10.dummyValue<_i8.Result<void>>(
                this,
                Invocation.method(#deleteMessage, [messageId]),
              ),
            ),
            returnValueForMissingStub: _i3.Future<_i8.Result<void>>.value(
              _i10.dummyValue<_i8.Result<void>>(
                this,
                Invocation.method(#deleteMessage, [messageId]),
              ),
            ),
          )
          as _i3.Future<_i8.Result<void>>);

  @override
  _i3.Future<_i8.Result<void>> deleteMessagesAfter(
    String? sessionId,
    int? afterSequence,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#deleteMessagesAfter, [sessionId, afterSequence]),
            returnValue: _i3.Future<_i8.Result<void>>.value(
              _i10.dummyValue<_i8.Result<void>>(
                this,
                Invocation.method(#deleteMessagesAfter, [
                  sessionId,
                  afterSequence,
                ]),
              ),
            ),
            returnValueForMissingStub: _i3.Future<_i8.Result<void>>.value(
              _i10.dummyValue<_i8.Result<void>>(
                this,
                Invocation.method(#deleteMessagesAfter, [
                  sessionId,
                  afterSequence,
                ]),
              ),
            ),
          )
          as _i3.Future<_i8.Result<void>>);

  @override
  _i3.Future<_i8.Result<void>> updateMessageContent(
    String? messageId,
    String? newContent,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#updateMessageContent, [messageId, newContent]),
            returnValue: _i3.Future<_i8.Result<void>>.value(
              _i10.dummyValue<_i8.Result<void>>(
                this,
                Invocation.method(#updateMessageContent, [
                  messageId,
                  newContent,
                ]),
              ),
            ),
            returnValueForMissingStub: _i3.Future<_i8.Result<void>>.value(
              _i10.dummyValue<_i8.Result<void>>(
                this,
                Invocation.method(#updateMessageContent, [
                  messageId,
                  newContent,
                ]),
              ),
            ),
          )
          as _i3.Future<_i8.Result<void>>);

  @override
  _i3.Future<int?> getMessageSequence(String? messageId) =>
      (super.noSuchMethod(
            Invocation.method(#getMessageSequence, [messageId]),
            returnValue: _i3.Future<int?>.value(),
            returnValueForMissingStub: _i3.Future<int?>.value(),
          )
          as _i3.Future<int?>);
}

/// A class which mocks [ChatBackupService].
///
/// See the documentation for Mockito's code generation for more information.
class MockChatBackupService extends _i1.Mock implements _i12.ChatBackupService {
  @override
  _i3.Future<void> enqueueMessageUpsert({
    required String? userId,
    required String? sessionId,
    required String? messageId,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#enqueueMessageUpsert, [], {
              #userId: userId,
              #sessionId: sessionId,
              #messageId: messageId,
            }),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);

  @override
  _i3.Future<void> enqueueSessionUpsert({
    required String? userId,
    required String? sessionId,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#enqueueSessionUpsert, [], {
              #userId: userId,
              #sessionId: sessionId,
            }),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);

  @override
  _i3.Future<void> processPendingJobs({String? userId}) =>
      (super.noSuchMethod(
            Invocation.method(#processPendingJobs, [], {#userId: userId}),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);

  @override
  _i3.Future<bool> restoreSessionMessagesIfEmpty(
    String? userId,
    String? sessionId,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#restoreSessionMessagesIfEmpty, [
              userId,
              sessionId,
            ]),
            returnValue: _i3.Future<bool>.value(false),
            returnValueForMissingStub: _i3.Future<bool>.value(false),
          )
          as _i3.Future<bool>);

  @override
  _i3.Future<bool> restoreFromBackupIfLocalEmpty(String? userId) =>
      (super.noSuchMethod(
            Invocation.method(#restoreFromBackupIfLocalEmpty, [userId]),
            returnValue: _i3.Future<bool>.value(false),
            returnValueForMissingStub: _i3.Future<bool>.value(false),
          )
          as _i3.Future<bool>);
}

/// A class which mocks [FeedbackService].
///
/// See the documentation for Mockito's code generation for more information.
class MockFeedbackService extends _i1.Mock implements _i13.FeedbackService {
  @override
  _i3.Future<void> saveFeedback({
    required String? userId,
    required String? messageId,
    required String? sessionId,
    required _i11.MessageFeedback? feedback,
    required String? messageContent,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#saveFeedback, [], {
              #userId: userId,
              #messageId: messageId,
              #sessionId: sessionId,
              #feedback: feedback,
              #messageContent: messageContent,
            }),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);
}

/// A class which mocks [ChatSessionManager].
///
/// See the documentation for Mockito's code generation for more information.
class MockChatSessionManager extends _i1.Mock
    implements _i14.ChatSessionManager {
  @override
  _i3.Future<String> getOrCreateFreshSession({
    required String? userId,
    required String? agentId,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#getOrCreateFreshSession, [], {
              #userId: userId,
              #agentId: agentId,
            }),
            returnValue: _i3.Future<String>.value(
              _i10.dummyValue<String>(
                this,
                Invocation.method(#getOrCreateFreshSession, [], {
                  #userId: userId,
                  #agentId: agentId,
                }),
              ),
            ),
            returnValueForMissingStub: _i3.Future<String>.value(
              _i10.dummyValue<String>(
                this,
                Invocation.method(#getOrCreateFreshSession, [], {
                  #userId: userId,
                  #agentId: agentId,
                }),
              ),
            ),
          )
          as _i3.Future<String>);

  @override
  _i3.Future<List<_i9.ChatSession>> getSessionsForAgent({
    required String? userId,
    required String? agentId,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#getSessionsForAgent, [], {
              #userId: userId,
              #agentId: agentId,
            }),
            returnValue: _i3.Future<List<_i9.ChatSession>>.value(
              <_i9.ChatSession>[],
            ),
            returnValueForMissingStub: _i3.Future<List<_i9.ChatSession>>.value(
              <_i9.ChatSession>[],
            ),
          )
          as _i3.Future<List<_i9.ChatSession>>);
}

/// A class which mocks [PostHogAnalyticsService].
///
/// See the documentation for Mockito's code generation for more information.
class MockPostHogAnalyticsService extends _i1.Mock
    implements _i15.PostHogAnalyticsService {
  @override
  _i3.Future<void> trackEvent(
    String? event, {
    Map<String, Object>? properties,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#trackEvent, [event], {#properties: properties}),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);

  @override
  _i3.Future<void> identifyUser(String? uid, {Map<String, Object>? traits}) =>
      (super.noSuchMethod(
            Invocation.method(#identifyUser, [uid], {#traits: traits}),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);

  @override
  _i3.Future<void> screenView(String? screenName) =>
      (super.noSuchMethod(
            Invocation.method(#screenView, [screenName]),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);

  @override
  _i3.Future<void> reset() =>
      (super.noSuchMethod(
            Invocation.method(#reset, []),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);
}
