"""
Engagement system data models.

EngagementDecision — Output of DecisionEngine (pure Python, no LLM).
NotificationOutput — Output of specialist agents (LLM-generated copy).
ReEngagementOutput — Output of ReEngagementAgent for follow-up notifications.

All Pydantic models use strict=True to catch bad LLM output immediately
rather than silently coercing wrong types.
"""

from __future__ import annotations

from typing import Any, Literal

from pydantic import BaseModel, ConfigDict


# ── Decision engine output ────────────────────────────────────────────────────

class EngagementDecision(BaseModel):
    """Pure-Python decision — no LLM. See DecisionEngine in decision_engine.py."""
    model_config = ConfigDict(strict=True)

    should_engage: bool
    chosen_agent: Literal[
        "habit_nudge",
        "calendar_prep",
        "memory_recall",
        "none",
    ]
    delay_minutes: int
    tone: Literal["roast", "warn", "educate", "celebrate", "check_in"]
    engagement_context: dict[str, Any]
    suppression_reason: str | None = None


# ── Specialist agent output ───────────────────────────────────────────────────

class NotificationOutput(BaseModel):
    """Copy generated by a specialist agent (LLM call via ModelProvider.cheap())."""
    model_config = ConfigDict(strict=True)

    title: str                   # max ~50 chars — shown as notification headline
    body: str                    # max ~100 chars — notification body text
    opening_chat_message: str    # first message Juno "says" when user taps + opens chat
    suggested_replies: list[str] # quick-tap chips shown below the opening message


class ReEngagementOutput(BaseModel):
    """Follow-up copy generated by ReEngagementAgent when user hasn't responded."""
    model_config = ConfigDict(strict=True)

    title: str
    body: str
    opening_chat_message: str
    escalation_level: int        # 1 = gentle nudge, 2 = general check-in
